#!/bin/bash

echo Script Running

echo Adding Libraries

module add languages/intel-compiler-16

module add openmpi/intel/64/1.6.5

module add tools/intel_builds/tau-2.23.1-openmpi

module add languages/python-2.7.6

module list

chmod +x bashScript
